services:
  web:
    build: .
    command: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p 8000 django_mastery.asgi:application"
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A django_mastery worker -l info
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  static_volume:
  redis_data:
